C#/Sample-dotnet-4.5/PayPing.Ipg/Controllers/PayPingController.cs
using PayPing.Ipg.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using config = System.Configuration.ConfigurationManager;

namespace PayPing.Ipg.Controllers
{

    [RoutePrefix("v1/[controller]/[action]")]
    public class PayPingController : Controller
    {
        private static string _accessToken { get; set; }

        public ActionResult Index()
        {
            _accessToken = Request.QueryString["accessToken"];
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Pay(RequestPayment model)
        {
            // ساخت کد پرداخت به منظور هدایت به درگاه بانکی
            var payCode = await CallApi<PaymentResult>(config.AppSettings["PAYMENT_URL"], model);

            //هدایت کاربر به درگاه بانک
            return Redirect(config.AppSettings["GOTOIPG_URL"] + payCode.Code);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="refid">شناسه پرداخت می باشد که به کمک آن یک پرداخت تایید و یا اصطلاحا وریفای می شود</param>
        /// <param name="clientrefid">کد و یا عبارت اختصاصی است که توسط کاربر برای سرویس پرداخت در زمان ساخت پرداخت ارسال شده است وبعد از برگشت از درگاه برای پذیرنده ارسال می گردد            </param>
        /// <param name="cardnumber">
        /// شماره کارت پرداخت کننده. برای داشتن این پارامتر باید عبارت rrn
        /// در پایان ReturnUrl اضافه نمایید
        /// تا بعد از برگشت از درگاه، به آدرس برگشت اضافه گردد
        /// </param>
        /// <returns></returns>
        [HttpPost]
        public virtual async Task<ActionResult> PaypingVerify(string refid, string clientrefid, string cardnumber)
        {
            var verifyBody = new RequestVerify
            {
                Amount = 100, // مبلغ به توامن می باشد
                RefId = refid
            };

            // اگر وریفای با موفقیت انجام پذیرد، تنها وضعیت 200 را برگشت می دهد و حاوی هیچ دیتایی نیست
            // اما اگر به هر دلیلی ادامه فرایند وریفای مقدور نباشد، 400 برگشت می دهد به همراه یک متن خطا
            var result = await CallApi<ResponseVerifyViewModel>(config.AppSettings["VERIFY_URL"], verifyBody);
            return View("verify", result);
        }
        
        private async Task<T> CallApi<T>(string apiUrl, object value, bool isToken = false) where T : class
        {
            var url = new Uri(apiUrl);
            var baseHost = $"{url.Scheme}://{url.Authority}";
            var method = $"{url.AbsolutePath}";
            var _client = new RestClient(baseHost) { Timeout = 20000 };
            var request = new RestRequest(method, Method.POST);
            if (isToken)
                request.AddObject(value);
            else
            {
                _client.AddDefaultHeader("Authorization", $"bearer {_accessToken}");
                request.AddJsonBody(value);
            }
            var response = await _client.ExecuteTaskAsync<T>(request);
            if (method.Contains("verify"))
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    var result = new ResponseVerifyViewModel { Message = "پرداخت شما با موفقیت انجام پذیرفت" };
                    return result as T;
                }
                else
                {
                    var result = new ResponseVerifyViewModel { Message = response.Content };
                    return result as T;
                }
            return response.Data;
        }
    }
}

C#/Sample-dotnet-4.5/PayPing.Ipg/Views/PayPing/Index.cshtml

@{
    ViewBag.Title = "Index";
}

@model PayPing.Ipg.Models.RequestPayment


@using (Html.BeginForm("Pay", "PayPing", FormMethod.Post))
{
<div >
    <div class="row col-md-12 pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.Amount)
            @Html.TextBoxFor(m => m.Amount, new { @class = "pay-input"  , Value = 100 })
        </div>
    </div>
    <div class="row col-md-12  pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.PayerName)
            @Html.TextBoxFor(m => m.PayerName, new { @class = "pay-input", Value = "پی پینگ" })
        </div>
    </div>
    <div class="row col-md-12  pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.PayerIdentity)
            @Html.TextBoxFor(m => m.PayerIdentity, new { @class = "pay-input", Value = "info@payping.ir" })
        </div>
    </div>
    <div class="row col-md-12  pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.ClientRefId)
            @Html.TextBoxFor(m => m.ClientRefId, new { @class = "pay-input", Value = "123" })
        </div>
    </div>
    <div class="row col-md-12 pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.ReturnUrl)
            @Html.TextBoxFor(m => m.ReturnUrl, new { @class = "pay-input", Value = $"{Request.Url.Scheme}://{Request.Url.Authority}/v1/PayPing/PaypingVerify" })
        </div>
    </div>
    <div class="row col-md-12 pay-row center">
        <div class="col-md-8 center">
            @Html.LabelFor(r => r.Description)
            @Html.TextBoxFor(m => m.Description, new { @class = "pay-input", Value = "بابت تنخواه شماره 123" })
        </div>
    </div>

    <div class="row col-md-12 center">
            <input type="submit" name="pay" id="pay" class="btn pay-button btn-success col-md-7" value="پرداخت" />
    </div>
</div>
}

C#/Sample-dotnet-4.5/PayPing.Ipg/Views/PayPing/verify.cshtml

@{
    ViewBag.Title = "verify";
}
@model PayPing.Ipg.Models.ResponseVerifyViewModel

<div class="row col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        <h2>@Html.DisplayName(Model.Message ?? "Error")</h2>
    </div>
</div>

